import { useEffect } from 'react';
import { Navigate, useParams } from 'react-router-dom';

/**
 * Handles `/state/:code` requests inside the SPA.
 *
 * The static HTML files at `public/state/{code}.html` (generated by the
 * pipeline) handle direct visits and crawler requests — they carry the
 * per-state OG meta and a meta-refresh to `/?state={CODE}`. But once the
 * SPA is loaded, React Router intercepts internal <Link to="/state/xx">
 * clicks before the static file is ever fetched, so the static-page
 * redirect never runs. Without this route, /rankings → state link would
 * hit the "*" catch-all and render NotFound.
 *
 * We resolve it client-side by redirecting to `/?state={CODE}`, which
 * Home.tsx already knows how to consume (it opens the matching state
 * panel on load).
 *
 * `replace` means the user's history entry for /state/xx is replaced
 * with /?state=XX — so Back goes to /rankings, not to a redirect dead
 * end.
 */
export function StateRedirect() {
  const { code } = useParams<{ code: string }>();
  const upper = (code ?? '').toUpperCase();

  // Light safety: only redirect for plausible 2-letter codes. Bogus paths
  // fall through to the NotFound catch-all via the early return.
  const isValid = /^[A-Z]{2}$/.test(upper);

  // Render a brief loading state in the (unlikely) frame before the
  // navigation effect fires — same look as the page-load spinner.
  useEffect(() => {
    // The <Navigate> below handles the actual redirect declaratively,
    // but this effect is here so the comment above is the only thing
    // someone reading the file has to understand. Nothing to do.
  }, []);

  if (!isValid) {
    return <Navigate to="/" replace />;
  }
  return <Navigate to={`/?state=${upper}`} replace />;
}
