import { Suspense, lazy, useCallback, useEffect, useMemo, useRef } from 'react';
import { Link } from 'react-router-dom';
import { quotientTable } from '../lib/allocation';
import type { StateProjection, ProjectionMeta } from '../lib/types';

// Recharts is ~150 KB gzipped and only renders inside this panel — keep it
// out of the initial bundle so the homepage LCP doesn't pay for it. The
// chunk loads the first time a user opens any state detail.
const PollingTrendChart = lazy(() => import('./PollingTrendChart'));

function ChartSkeleton() {
  // Matches the actual chart's container height + a soft pulse so there's
  // no layout shift when the chunk resolves.
  return (
    <div
      className="w-full h-48 rounded-md bg-stone-100 animate-pulse"
      aria-hidden="true"
    />
  );
}

interface Props {
  state: StateProjection;
  meta: ProjectionMeta;
  allStates: StateProjection[];
  onClose: () => void;
}

export function StateDetail({ state, meta, allStates, onClose }: Props) {
  const headingRef = useRef<HTMLHeadingElement | null>(null);

  const handleDownloadImage = useCallback(() => {
    // The pipeline pre-renders a clean 1200×630 brand card for each state at
    // /og/state-{CODE}.png. Download it directly — much better artifact than
    // a DOM-screenshot of the panel.
    const link = document.createElement('a');
    link.href = `/og/state-${state.code}.png`;
    link.download = `proportional-house-${state.code.toLowerCase()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [state.code]);

  const handleShareTwitter = useCallback(() => {
    // Link to the per-state static HTML page (generated by the pipeline) — it
    // carries the og:image meta tag so Twitter/X will render the brand card
    // as the unfurled preview. Compose the tweet text around the headline
    // delegation shift so even without the image the message reads.
    const dGain = state.projected.d_seats - state.actual.d_seats;
    let shiftPhrase: string;
    if (dGain > 0) {
      shiftPhrase = `would gain ${dGain} Democratic seat${dGain === 1 ? '' : 's'}`;
    } else if (dGain < 0) {
      shiftPhrase = `would gain ${Math.abs(dGain)} Republican seat${Math.abs(dGain) === 1 ? '' : 's'}`;
    } else {
      shiftPhrase = `looks the same`;
    }
    const text = `${state.name} ${shiftPhrase} under proportional representation:`;
    const url = `${window.location.origin}/state/${state.code.toLowerCase()}`;
    const intent =
      'https://twitter.com/intent/tweet?text=' +
      encodeURIComponent(text) +
      '&url=' +
      encodeURIComponent(url);
    window.open(intent, '_blank', 'noopener,noreferrer');
  }, [state.code, state.name, state.actual.d_seats, state.projected.d_seats]);

  // Focus the heading on open so screen-reader users land inside the dialog,
  // and listen for Escape to close.
  useEffect(() => {
    headingRef.current?.focus();
  }, [state.fips]);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onClose();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  const dGain = state.projected.d_seats - state.actual.d_seats;

  // "See also": find 3 states with the most similar PR distortion. Same
  // direction as the current state (both gain D, or both gain R), closest
  // absolute delta. Falls back to nearest distortion regardless of sign
  // if there aren't enough same-sign matches.
  const similarStates = useMemo(() => {
    if (!allStates || allStates.length === 0) return [];
    const others = allStates.filter((s) => s.fips !== state.fips);
    const withDelta = others.map((s) => ({
      state: s,
      delta: s.projected.d_seats - s.actual.d_seats,
    }));
    const sameSign = dGain === 0
      ? withDelta.filter((x) => x.delta === 0)
      : withDelta.filter((x) => Math.sign(x.delta) === Math.sign(dGain));
    // Sort by how close their delta is to ours.
    const pool = sameSign.length >= 3 ? sameSign : withDelta;
    return pool
      .map((x) => ({ ...x, distance: Math.abs(x.delta - dGain) }))
      .sort((a, b) => a.distance - b.distance)
      .slice(0, 3)
      .map((x) => x.state);
  }, [allStates, state.fips, dGain]);

  const quotients = useMemo(() => {
    if (state.seats <= 1) return [];
    return quotientTable(
      {
        seats: state.seats,
        d_votes: state.projected.d_share * 1_000_000,
        r_votes: state.projected.r_share * 1_000_000,
      },
      'sainte-lague',
    );
  }, [state]);

  return (
    <aside
      className={[
        // Mobile: bottom sheet — covers ~78% of viewport with rounded top corners.
        'fixed bottom-0 left-0 right-0 max-h-[78vh] rounded-t-2xl',
        'bg-white border-t border-stone-200 shadow-2xl overflow-y-auto',
        // Desktop: revert to the right-side sidebar.
        'sm:top-0 sm:bottom-0 sm:left-auto sm:max-h-none sm:w-[28rem] sm:rounded-none sm:border-t-0 sm:border-l',
      ].join(' ')}
      role="dialog"
      aria-modal="true"
      aria-label={`${state.name} detail`}
    >
      {/* Visual drag-handle affordance, mobile only. */}
      <div aria-hidden="true" className="sm:hidden flex justify-center pt-2 pb-1">
        <span className="block h-1.5 w-12 rounded-full bg-stone-300" />
      </div>
      <div className="px-5 pt-3 sm:pt-5 pb-5 border-b border-stone-200 flex items-start justify-between gap-3">
        <div>
          <div className="text-xs uppercase tracking-wider text-stone-500 font-medium">{state.code}</div>
          <h2 ref={headingRef} tabIndex={-1} className="text-xl font-semibold text-stone-900 outline-none">{state.name}</h2>
          <div className="text-sm text-stone-600">
            {state.seats} {state.seats === 1 ? 'seat' : 'seats'}
          </div>
        </div>
        <div className="flex items-center gap-1 flex-shrink-0">
          <button
            type="button"
            onClick={handleShareTwitter}
            className="text-stone-500 hover:text-stone-900 hover:bg-stone-100 rounded-full h-11 w-11 flex items-center justify-center"
            aria-label="Share on X (Twitter)"
            title="Share on X (Twitter)"
          >
            {/* X logo — the current Twitter/X mark. */}
            <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
          </button>
          <button
            type="button"
            onClick={handleDownloadImage}
            className="text-stone-500 hover:text-stone-900 hover:bg-stone-100 rounded-full h-11 w-11 flex items-center justify-center"
            aria-label="Save as image"
            title="Save as image"
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
          </button>
          <button
            type="button"
            onClick={onClose}
            className="text-stone-500 hover:text-stone-900 hover:bg-stone-100 rounded-full h-11 w-11 flex items-center justify-center text-2xl leading-none"
            aria-label="Close"
          >
            ×
          </button>
        </div>
      </div>

      <div className="p-5 space-y-5">
        {(state.imputed_district_count ?? 0) > 0 && (
          <div className="text-sm border border-blue-200 bg-blue-50 text-blue-900 rounded-md px-3 py-2">
            <strong>
              {state.imputed_district_count === 1
                ? '1 district imputed from presidential vote.'
                : `${state.imputed_district_count} districts imputed from presidential vote.`}
            </strong>{' '}
            {state.imputed_district_ids?.join(', ') ?? ''}{' '}
            had no major-party opponent in 2024; we replaced the district's House two-party total with its 2024 presidential two-party split so the baseline reflects partisan lean rather than no-contest. See methodology.
          </div>
        )}

        {state.baseline_distortion_warning && (state.imputed_district_count ?? 0) === 0 && (
          <div className="text-sm border border-amber-200 bg-amber-50 text-amber-900 rounded-md px-3 py-2">
            <strong>Baseline distortion warning.</strong>{' '}
            One major party fielded no candidate statewide in 2024, so the 2024 two-party share isn't meaningful for this state. The projection here assumes a neutral 50/50 baseline before applying the national swing.
          </div>
        )}

        <Comparison
          label="Delegation"
          left={{ heading: 'Actual today', d: state.actual.d_seats, r: state.actual.r_seats }}
          right={{ heading: 'Projected under PR', d: state.projected.d_seats, r: state.projected.r_seats }}
        />

        {dGain !== 0 && (
          <div className="text-sm">
            Under PR this state{' '}
            <span className={dGain > 0 ? 'text-blue-700 font-medium' : 'text-red-700 font-medium'}>
              {dGain > 0 ? `gains ${dGain} D seat${Math.abs(dGain) === 1 ? '' : 's'}`
                         : `gains ${Math.abs(dGain)} R seat${Math.abs(dGain) === 1 ? '' : 's'}`}
            </span>{' '}
            relative to today.
          </div>
        )}

        <Section title="Vote share">
          <div className="grid grid-cols-2 gap-3 text-sm">
            <ShareBlock heading="2024 baseline" d={state.baseline_2024.d_share} r={state.baseline_2024.r_share} />
            <ShareBlock heading="Projected 2026" d={state.projected.d_share} r={state.projected.r_share} />
          </div>
          <div className="text-xs text-stone-500 mt-2">
            {(() => {
              const stateSwing = state.state_swing_applied ?? meta.swing;
              const elasticity = state.state_elasticity ?? 1.0;
              const showMultiplier = Math.abs(elasticity - 1.0) > 0.05;
              const swingLabel = `${stateSwing >= 0 ? '+' : ''}${stateSwing.toFixed(1)} pts toward ${stateSwing >= 0 ? 'D' : 'R'}`;
              return (
                <>
                  Swing applied to this state: <span className={stateSwing >= 0 ? 'font-medium text-blue-700' : 'font-medium text-red-700'}>{swingLabel}</span>
                  {showMultiplier && (
                    <>
                      {' '}<span className="text-stone-400">
                        (national swing {meta.swing >= 0 ? '+' : ''}{meta.swing.toFixed(1)} × elasticity {elasticity.toFixed(2)}×)
                      </span>
                    </>
                  )}
                </>
              );
            })()}
          </div>
        </Section>

        {state.seats > 1 && quotients.length > 0 && (
          <details className="text-sm">
            <summary className="cursor-pointer text-stone-700 font-medium">Show the math (Sainte-Laguë)</summary>
            <div className="mt-3 overflow-x-auto">
              <table className="w-full text-xs tabular-nums">
                <thead className="text-stone-500 text-left">
                  <tr>
                    <th className="py-1 pr-3">÷</th>
                    <th className="py-1 pr-3 text-blue-700">D</th>
                    <th className="py-1 pr-3 text-red-700">R</th>
                  </tr>
                </thead>
                <tbody>
                  {quotients.map((row) => (
                    <tr key={row.divisor} className="border-t border-stone-100">
                      <td className="py-1 pr-3 text-stone-500">{row.divisor}</td>
                      <td className={`py-1 pr-3 ${row.d_wins ? 'font-semibold text-blue-700' : 'text-stone-400'}`}>
                        {row.d_quotient.toFixed(0)}
                        {row.d_wins && ' ✓'}
                      </td>
                      <td className={`py-1 pr-3 ${row.r_wins ? 'font-semibold text-red-700' : 'text-stone-400'}`}>
                        {row.r_quotient.toFixed(0)}
                        {row.r_wins && ' ✓'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="text-xs text-stone-500 mt-2">
                Top {state.seats} quotients win seats. ✓ marks seat-winning quotients.
              </div>
            </div>
          </details>
        )}

        <Section title="National polling trend, last 180 days">
          <Suspense fallback={<ChartSkeleton />}>
            <PollingTrendChart currentAverageMargin={meta.generic_ballot_margin} />
          </Suspense>
          <p className="text-xs text-stone-500 mt-2">
            Each dot is one poll; size scales with sample size. The navy line is the same 14-day weighted average we use in the projection. Source: Silver Bulletin's public generic-ballot database.
          </p>
        </Section>

        {similarStates.length > 0 && (
          <Section title="See also — similar distortions">
            <div className="flex flex-wrap gap-2">
              {similarStates.map((s) => {
                const delta = s.projected.d_seats - s.actual.d_seats;
                const label = delta === 0 ? '±0' : delta > 0 ? `+${delta} D` : `+${Math.abs(delta)} R`;
                const labelClass = delta === 0
                  ? 'text-stone-500'
                  : delta > 0 ? 'text-blue-700' : 'text-red-700';
                return (
                  <Link
                    key={s.fips}
                    to={`/state/${s.code.toLowerCase()}`}
                    className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-stone-100 text-stone-700 text-xs hover:bg-stone-200 hover:text-stone-900 transition-colors"
                  >
                    <span>{s.name}</span>
                    <span className={`font-medium tabular-nums ${labelClass}`}>{label}</span>
                  </Link>
                );
              })}
            </div>
          </Section>
        )}
      </div>
    </aside>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-xs uppercase tracking-wider text-stone-500 font-medium mb-2">{title}</h3>
      {children}
    </div>
  );
}

function Comparison({
  label,
  left,
  right,
}: {
  label: string;
  left: { heading: string; d: number; r: number };
  right: { heading: string; d: number; r: number };
}) {
  return (
    <div>
      <h3 className="text-xs uppercase tracking-wider text-stone-500 font-medium mb-2">{label}</h3>
      <div className="grid grid-cols-2 gap-3">
        <SeatStrip {...left} />
        <SeatStrip {...right} />
      </div>
    </div>
  );
}

function SeatStrip({ heading, d, r }: { heading: string; d: number; r: number }) {
  const total = d + r;
  const dPct = total > 0 ? (d / total) * 100 : 0;
  return (
    <div>
      <div className="text-xs text-stone-500">{heading}</div>
      <div className="mt-1 flex items-baseline gap-2">
        <span className="text-blue-700 font-semibold text-lg tabular-nums">{d}</span>
        <span className="text-stone-400 text-sm">·</span>
        <span className="text-red-700 font-semibold text-lg tabular-nums">{r}</span>
      </div>
      <div className="mt-1 h-2 rounded-full bg-stone-100 overflow-hidden flex">
        <div className="bg-blue-700" style={{ width: `${dPct}%` }} aria-hidden />
        <div className="bg-red-700 flex-1" aria-hidden />
      </div>
    </div>
  );
}

function ShareBlock({ heading, d, r }: { heading: string; d: number; r: number }) {
  return (
    <div>
      <div className="text-xs text-stone-500">{heading}</div>
      <div className="mt-1 tabular-nums">
        <span className="text-blue-700 font-medium">{(d * 100).toFixed(1)}%</span>
        <span className="text-stone-400"> · </span>
        <span className="text-red-700 font-medium">{(r * 100).toFixed(1)}%</span>
      </div>
    </div>
  );
}
