import { useCallback, useEffect, useMemo, useRef } from 'react';
import { Link } from 'react-router-dom';
import { quotientTable } from '../lib/allocation';
import { METHOD_LABELS, type AllocationMethodKind } from '../lib/methods';
import { PARTY_D, PARTY_R, displayName } from '../lib/parties';
import { DEFAULT_HOUSE_SIZE } from '../lib/sandboxSwing';
import type { SandboxStateProjection } from '../lib/sandboxTypes';
import { SeatStrip } from './SeatStrip';
import { StateRetroHistory } from './StateRetroHistory';
import type { StateProjection, ProjectionMeta, StateRetroPoint } from '../lib/types';

export interface StateDetailContentProps {
  state: StateProjection;
  meta: ProjectionMeta;
  allStates: StateProjection[];
  /**
   * Callback for "user wants to close the dialog". The shell is responsible
   * for any close animation; this callback is the final state mutation that
   * unmounts the detail panel.
   */
  onClose: () => void;
  /**
   * If true (default), the shell is rendering inside a dialog and the
   * close/share/download/header buttons should be visible. The /embed/state/
   * view passes false to render the content standalone with no shell chrome.
   */
  showHeaderControls?: boolean;
  /**
   * If true (default), focus the state-name heading on mount so screen
   * readers land inside the dialog. Embedded use cases that render this
   * inline in a page set false to avoid stealing focus.
   */
  autoFocusHeading?: boolean;
  /**
   * Sandbox-derived per-state slice. When present:
   *   - If `parties.length > 2` (minors active), render N-party delegation +
   *     vote-share blocks.
   *   - If `parties.length === 2`, render the two-party UI but pull projected
   *     D / R seats and shares from sandboxState (so method + house-size
   *     changes update the panel).
   * When absent, render the two-party UI from `state.projected` (the static
   * pipeline value, used in Current / Retrospective and in the /embed view).
   */
  sandboxState?: SandboxStateProjection | null;
  /**
   * Active allocation method. Affects the math-demo visibility (hidden under
   * non-PR methods because the Sainte-Laguë quotient table wouldn't match the
   * actual allocation) and the "Projected under …" headings + settings line.
   */
  method?: AllocationMethodKind;
  /**
   * Display label override for the active method (e.g. "MMD-4" / "MMP-30"
   * when a magnitude/share slider is dialed off a preset). When omitted the
   * label is derived from `method`.
   */
  methodLabel?: string;
  /** Active sandbox House size — drives the settings-line badge when expanded past 435. */
  houseSize?: number;
  /** Active sandbox per-state threshold (0–1) — drives the settings-line badge when minors are active. */
  threshold?: number;
  /**
   * Per-cycle PR-vs-actual history for this state (2016–2024), from
   * retrospectives.json. Optional — only the Home views pass it; the embed
   * route and Sandbox leave it undefined, hiding the section.
   */
  retroHistory?: StateRetroPoint[];
}

export function StateDetailContent({
  state,
  meta,
  allStates,
  onClose,
  showHeaderControls = true,
  autoFocusHeading = true,
  sandboxState,
  method = 'PR',
  methodLabel: methodLabelOverride,
  houseSize = DEFAULT_HOUSE_SIZE,
  threshold,
  retroHistory,
}: StateDetailContentProps) {
  const headingRef = useRef<HTMLHeadingElement | null>(null);

  // Keep "PR" short so the embed view and default sandbox still read
  // "Projected under PR"; reforms read "MMD-3", "MMP-50", "PR (D'Hondt)", etc.
  // An explicit override (from a slider-dialed value, e.g. "MMD-4") wins.
  const methodLabel = methodLabelOverride ?? (method === 'PR' ? 'PR' : METHOD_LABELS[method]);

  const handleDownloadImage = useCallback(() => {
    // The pipeline pre-renders a clean 1200×630 brand card for each state at
    // /og/state-{CODE}.png. Download it directly — much better artifact than
    // a DOM-screenshot of the panel.
    const link = document.createElement('a');
    link.href = `/og/state-${state.code}.png`;
    link.download = `proportional-house-${state.code.toLowerCase()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [state.code]);

  const handleShareTwitter = useCallback(() => {
    // Link to the per-state static HTML page (generated by the pipeline) — it
    // carries the og:image meta tag so Twitter/X will render the brand card
    // as the unfurled preview. Compose the tweet text around the headline
    // delegation shift so even without the image the message reads.
    const dGain = state.projected.d_seats - state.actual.d_seats;
    let shiftPhrase: string;
    if (dGain > 0) {
      shiftPhrase = `would gain ${dGain} Democratic seat${dGain === 1 ? '' : 's'}`;
    } else if (dGain < 0) {
      shiftPhrase = `would gain ${Math.abs(dGain)} Republican seat${Math.abs(dGain) === 1 ? '' : 's'}`;
    } else {
      shiftPhrase = `looks the same`;
    }
    const text = `${state.name} ${shiftPhrase} under proportional representation:`;
    const url = `${window.location.origin}/state/${state.code.toLowerCase()}`;
    const intent =
      'https://twitter.com/intent/tweet?text=' +
      encodeURIComponent(text) +
      '&url=' +
      encodeURIComponent(url);
    window.open(intent, '_blank', 'noopener,noreferrer');
  }, [state.code, state.name, state.actual.d_seats, state.projected.d_seats]);

  // Focus the heading on open so screen-reader users land inside the dialog.
  useEffect(() => {
    if (autoFocusHeading) {
      headingRef.current?.focus();
    }
  }, [state.fips, autoFocusHeading]);

  // "Has minors" controls the UI shape (N-party seat strip vs. 2-party).
  // "Use sandbox data" applies whenever sandboxState exists — so method +
  // house-size changes update the 2-party Comparison / Vote share too.
  const hasMinors =
    !!sandboxState &&
    sandboxState.parties.some(
      (p) => p.party.id !== 'D' && p.party.id !== 'R' && p.seats > 0,
    );
  const projectedD = sandboxState ? sandboxState.parties[0]?.seats ?? 0 : state.projected.d_seats;
  const projectedR = sandboxState ? sandboxState.parties[1]?.seats ?? 0 : state.projected.r_seats;
  const projectedDShare = sandboxState
    ? sandboxState.parties[0]?.vote_share ?? state.projected.d_share
    : state.projected.d_share;
  const projectedRShare = sandboxState
    ? sandboxState.parties[1]?.vote_share ?? state.projected.r_share
    : state.projected.r_share;
  const effectiveSeats = sandboxState ? sandboxState.total_seats : state.seats;
  // Baseline for the "shift under PR" comparison: today's delegation scaled to
  // the projected House size (so chamber growth isn't read as a partisan
  // swing). Equals the real actual when the House isn't expanded.
  const actualBaseD = sandboxState ? sandboxState.actual_scaled.d_seats : state.actual.d_seats;
  const actualBaseR = sandboxState ? sandboxState.actual_scaled.r_seats : state.actual.r_seats;
  const houseExpanded = !!sandboxState && sandboxState.total_seats !== state.seats;
  const actualHeading = houseExpanded ? `Today, scaled to ${effectiveSeats}` : 'Actual today';
  const dGain = projectedD - actualBaseD;

  // "See also": find 3 states with the most similar PR distortion. Same
  // direction as the current state (both gain D, or both gain R), closest
  // absolute delta. Falls back to nearest distortion regardless of sign
  // if there aren't enough same-sign matches.
  const similarStates = useMemo(() => {
    if (!allStates || allStates.length === 0) return [];
    const others = allStates.filter((s) => s.fips !== state.fips);
    const withDelta = others.map((s) => ({
      state: s,
      delta: s.projected.d_seats - s.actual.d_seats,
    }));
    const sameSign = dGain === 0
      ? withDelta.filter((x) => x.delta === 0)
      : withDelta.filter((x) => Math.sign(x.delta) === Math.sign(dGain));
    // Sort by how close their delta is to ours.
    const pool = sameSign.length >= 3 ? sameSign : withDelta;
    return pool
      .map((x) => ({ ...x, distance: Math.abs(x.delta - dGain) }))
      .sort((a, b) => a.distance - b.distance)
      .slice(0, 3)
      .map((x) => x.state);
  }, [allStates, state.fips, dGain]);

  const quotients = useMemo(() => {
    if (state.seats <= 1) return [];
    return quotientTable(
      {
        seats: state.seats,
        d_votes: state.projected.d_share * 1_000_000,
        r_votes: state.projected.r_share * 1_000_000,
      },
      'sainte-lague',
    );
  }, [state]);

  return (
    <>
      <div className="px-5 pt-3 sm:pt-5 pb-5 border-b border-stone-200 flex items-start justify-between gap-3">
        {/* min-w-0 lets the title block shrink past its intrinsic content
         * width so the buttons aren't pushed off-screen on narrow phones
         * with long state names like "Massachusetts". */}
        <div className="min-w-0 flex-1">
          <div className="text-xs uppercase tracking-wider text-stone-500 font-medium">{state.code}</div>
          <h2 ref={headingRef} tabIndex={-1} className="text-xl font-semibold text-stone-900 outline-none break-words">{state.name}</h2>
          <div className="text-sm text-stone-600">
            {effectiveSeats} {effectiveSeats === 1 ? 'seat' : 'seats'}
          </div>
        </div>
        {showHeaderControls && (
          <div className="flex items-center gap-1 flex-shrink-0">
            <button
              type="button"
              onClick={handleShareTwitter}
              className="text-stone-500 hover:text-stone-900 hover:bg-stone-100 rounded-full h-11 w-11 flex items-center justify-center"
              aria-label="Share on X (Twitter)"
              title="Share on X (Twitter)"
            >
              {/* X logo — the current Twitter/X mark. */}
              <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
              </svg>
            </button>
            <button
              type="button"
              onClick={handleDownloadImage}
              className="text-stone-500 hover:text-stone-900 hover:bg-stone-100 rounded-full h-11 w-11 flex items-center justify-center"
              aria-label="Save as image"
              title="Save as image"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="text-stone-500 hover:text-stone-900 hover:bg-stone-100 rounded-full h-11 w-11 flex items-center justify-center text-2xl leading-none"
              aria-label="Close"
            >
              ×
            </button>
          </div>
        )}
      </div>

      <div className="p-5 space-y-5">
        {sandboxState && (
          <div className="flex flex-wrap gap-1.5">
            <Badge>{methodLabel}</Badge>
            {houseSize !== DEFAULT_HOUSE_SIZE && <Badge>{houseSize}-seat House</Badge>}
            {sandboxState.parties.length > 2 && threshold != null && (
              <Badge>{+((threshold * 100).toFixed(1))}% threshold</Badge>
            )}
          </div>
        )}

        {(state.imputed_district_count ?? 0) > 0 && (
          <div className="text-sm border border-blue-200 bg-blue-50 text-blue-900 rounded-md px-3 py-2">
            <strong>
              {state.imputed_district_count === 1
                ? '1 district imputed from presidential vote.'
                : `${state.imputed_district_count} districts imputed from presidential vote.`}
            </strong>{' '}
            {state.imputed_district_ids?.join(', ') ?? ''}{' '}
            had no major-party opponent in 2024; we replaced the district’s House two-party total with its 2024 presidential two-party split so the baseline reflects partisan lean rather than no-contest. See methodology.
          </div>
        )}

        {state.baseline_distortion_warning && (state.imputed_district_count ?? 0) === 0 && (
          <div className="text-sm border border-amber-200 bg-amber-50 text-amber-900 rounded-md px-3 py-2">
            <strong>Baseline distortion warning.</strong>{' '}
            One major party fielded no candidate statewide in 2024, so the 2024 two-party share isn’t meaningful for this state. The projection here assumes a neutral 50/50 baseline before applying the national swing.
          </div>
        )}

        {hasMinors ? (
          <div>
            <h3 className="text-xs uppercase tracking-wider text-stone-500 font-medium mb-2">Delegation</h3>
            <div className="grid grid-cols-2 gap-3">
              <SeatStrip
                heading={actualHeading}
                parties={[
                  { id: 'D', label: 'D', color: PARTY_D.color, seats: actualBaseD },
                  { id: 'R', label: 'R', color: PARTY_R.color, seats: actualBaseR },
                ]}
              />
              <SeatStrip
                heading={`Projected under ${methodLabel}`}
                parties={sandboxState!.parties.map((p) => ({
                  id: p.party.id,
                  label: displayName(p.party),
                  color: p.party.color,
                  seats: p.seats,
                }))}
              />
            </div>
          </div>
        ) : (
          <Comparison
            label="Delegation"
            left={{ heading: actualHeading, d: actualBaseD, r: actualBaseR }}
            right={{ heading: `Projected under ${methodLabel}`, d: projectedD, r: projectedR }}
          />
        )}

        {hasMinors ? (
          // Minor-party gains paragraph: list any non-D/R party with seats.
          (() => {
            const minors = sandboxState!.parties.filter(
              (p) => p.party.id !== 'D' && p.party.id !== 'R' && p.seats > 0,
            );
            if (minors.length === 0) return null;
            return (
              <div className="text-sm">
                {minors.map((m, i) => (
                  <span key={m.party.id}>
                    {i > 0 && ' · '}
                    <span className="font-medium" style={{ color: m.party.color }}>
                      {m.party.label} {m.seats} seat{m.seats === 1 ? '' : 's'}
                    </span>
                  </span>
                ))}
                {' '}from a {(minors.reduce((s, m) => s + m.vote_share, 0) * 100).toFixed(1)}% combined vote share.
              </div>
            );
          })()
        ) : (
          dGain !== 0 && (
            <div className="text-sm">
              Under {methodLabel} this state{' '}
              <span className={dGain > 0 ? 'text-blue-700 font-medium' : 'text-red-700 font-medium'}>
                {dGain > 0 ? `gains ${dGain} D seat${Math.abs(dGain) === 1 ? '' : 's'}`
                           : `gains ${Math.abs(dGain)} R seat${Math.abs(dGain) === 1 ? '' : 's'}`}
              </span>{' '}
              relative to today.
            </div>
          )
        )}

        <Section title="Vote share">
          <div className="grid grid-cols-2 gap-3 text-sm">
            <ShareBlock heading="2024 baseline" d={state.baseline_2024.d_share} r={state.baseline_2024.r_share} />
            {hasMinors ? (
              <div>
                <div className="text-xs text-stone-500">Projected (sandbox)</div>
                <div className="mt-1 space-y-0.5">
                  {sandboxState!.parties.map((p) => (
                    <div key={p.party.id} className="tabular-nums">
                      <span className="font-medium" style={{ color: p.party.color }}>
                        {displayName(p.party)}
                      </span>{' '}
                      <span className="text-stone-700">{(p.vote_share * 100).toFixed(1)}%</span>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <ShareBlock heading="Projected 2026" d={projectedDShare} r={projectedRShare} />
            )}
          </div>
          <div className="text-xs text-stone-500 mt-2">
            {(() => {
              const stateSwing = state.state_swing_applied ?? meta.swing;
              const elasticity = state.state_elasticity ?? 1.0;
              const showMultiplier = Math.abs(elasticity - 1.0) > 0.05;
              const swingLabel = `${stateSwing >= 0 ? '+' : ''}${stateSwing.toFixed(1)} pts toward ${stateSwing >= 0 ? 'D' : 'R'}`;
              return (
                <>
                  Swing applied to this state: <span className={stateSwing >= 0 ? 'font-medium text-blue-700' : 'font-medium text-red-700'}>{swingLabel}</span>
                  {showMultiplier && (
                    <>
                      {' '}<span className="text-stone-400">
                        (national swing {meta.swing >= 0 ? '+' : ''}{meta.swing.toFixed(1)} × elasticity {elasticity.toFixed(2)}×)
                      </span>
                    </>
                  )}
                </>
              );
            })()}
          </div>
        </Section>

        {/* The math demo is Sainte-Laguë-specific. Under other PR formulas
          * (D'Hondt, Hamilton) or MMD/MMP, the quotients shown wouldn't
          * match the actual allocation, so hide it outside Pure PR. */}
        {state.seats > 1 && quotients.length > 0 && method === 'PR' && (
          <details className="text-sm">
            <summary className="cursor-pointer text-stone-700 font-medium">Show the math (Sainte-Laguë)</summary>
            <div className="mt-3 overflow-x-auto">
              <table className="w-full text-xs tabular-nums">
                <thead className="text-stone-500 text-left">
                  <tr>
                    <th className="py-1 pr-3">÷</th>
                    <th className="py-1 pr-3 text-blue-700">D</th>
                    <th className="py-1 pr-3 text-red-700">R</th>
                  </tr>
                </thead>
                <tbody>
                  {quotients.map((row) => (
                    <tr key={row.divisor} className="border-t border-stone-100">
                      <td className="py-1 pr-3 text-stone-500">{row.divisor}</td>
                      <td className={`py-1 pr-3 ${row.d_wins ? 'font-semibold text-blue-700' : 'text-stone-400'}`}>
                        {row.d_quotient.toFixed(0)}
                        {row.d_wins && ' ✓'}
                      </td>
                      <td className={`py-1 pr-3 ${row.r_wins ? 'font-semibold text-red-700' : 'text-stone-400'}`}>
                        {row.r_quotient.toFixed(0)}
                        {row.r_wins && ' ✓'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="text-xs text-stone-500 mt-2">
                Top {state.seats} quotients win seats. ✓ marks seat-winning quotients.
              </div>
            </div>
          </details>
        )}

        {retroHistory && retroHistory.length > 0 && (
          <Section title="Under PR, 2016–2024">
            <StateRetroHistory points={retroHistory} />
          </Section>
        )}

        {similarStates.length > 0 && (
          <Section title="See also: similar distortions">
            <div className="flex flex-wrap gap-2">
              {similarStates.map((s) => {
                const delta = s.projected.d_seats - s.actual.d_seats;
                const label = delta === 0 ? '±0' : delta > 0 ? `+${delta} D` : `+${Math.abs(delta)} R`;
                const labelClass = delta === 0
                  ? 'text-stone-500'
                  : delta > 0 ? 'text-blue-700' : 'text-red-700';
                return (
                  <Link
                    key={s.fips}
                    to={`/state/${s.code.toLowerCase()}`}
                    className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-stone-100 text-stone-700 text-xs hover:bg-stone-200 hover:text-stone-900 transition-colors"
                  >
                    <span>{s.name}</span>
                    <span className={`font-medium tabular-nums ${labelClass}`}>{label}</span>
                  </Link>
                );
              })}
            </div>
          </Section>
        )}
      </div>
    </>
  );
}

function Badge({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center rounded-full bg-stone-100 text-stone-600 text-[11px] font-medium px-2 py-0.5 tabular-nums">
      {children}
    </span>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-xs uppercase tracking-wider text-stone-500 font-medium mb-2">{title}</h3>
      {children}
    </div>
  );
}

function Comparison({
  label,
  left,
  right,
}: {
  label: string;
  left: { heading: string; d: number; r: number };
  right: { heading: string; d: number; r: number };
}) {
  // Convert {d, r} to the generic SeatStrip's parties array using the
  // canonical D/R presets so colors stay consistent with the rest of the
  // app (Map fills, NationalSummary numbers, etc.).
  const toParties = (d: number, r: number) => [
    { id: 'D', label: 'D', color: PARTY_D.color, seats: d },
    { id: 'R', label: 'R', color: PARTY_R.color, seats: r },
  ];
  return (
    <div>
      <h3 className="text-xs uppercase tracking-wider text-stone-500 font-medium mb-2">{label}</h3>
      <div className="grid grid-cols-2 gap-3">
        <SeatStrip heading={left.heading} parties={toParties(left.d, left.r)} />
        <SeatStrip heading={right.heading} parties={toParties(right.d, right.r)} />
      </div>
    </div>
  );
}

function ShareBlock({ heading, d, r }: { heading: string; d: number; r: number }) {
  return (
    <div>
      <div className="text-xs text-stone-500">{heading}</div>
      <div className="mt-1 tabular-nums">
        <span className="text-blue-700 font-medium">{(d * 100).toFixed(1)}%</span>
        <span className="text-stone-400"> · </span>
        <span className="text-red-700 font-medium">{(r * 100).toFixed(1)}%</span>
      </div>
    </div>
  );
}
